[workspace]
members = ["crates/ndc-graphql", "crates/ndc-graphql-cli", "crates/common"]
resolver = "2"

package.version = "0.2.0"
package.edition = "2021"

# insta performs better in release mode
[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
