[package]
name = "common"
version.workspace = true
edition.workspace = true

[dependencies]
glob-match = "0.2.1"
graphql_client = "0.14.0"
graphql-parser = "0.4.0"
reqwest = { version = "0.12.3", features = [
    "json",
    "rustls-tls",
], default-features = false }
schemars = "0.8.16"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
