name: "Test Suite"
on:
  pull_request:

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          # this defaults to "-D warnings", making warnings fail the entire build.
          # setting to empty strng to allow builds with warnings
          # todo: consider removing this, and disallowing pushing with warnings?
          rustflags: ""
      - run: cargo test --all-features

  # Check formatting with rustfmt
  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Ensure rustfmt is installed and setup problem matcher
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
          # this defaults to "-D warnings", making warnings fail the entire build.
          # setting to empty strng to allow builds with warnings
          # todo: consider removing this, and disallowing pushing with warnings?
          rustflags: ""
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1